site_name: AsyncBoto Docs
repo_name: SpielerNogard/AsyncBoto
repo_url: https://github.com/squidfunk/mkdocs-material

theme:
  name: material

plugins:
  search: null
#  macros:
#    include_yaml:
#    - external_links: ../en/data/external_links.yml
#    - github_sponsors: ../en/data/github_sponsors.yml
#    - people: ../en/data/people.yml
#    - contributors: ../en/data/contributors.yml
#    - translators: ../en/data/translators.yml
#    - translation_reviewers: ../en/data/translation_reviewers.yml
#    - skip_users: ../en/data/skip_users.yml
#    - members: ../en/data/members.yml
#    - sponsors_badge: ../en/data/sponsors_badge.yml
#    - sponsors: ../en/data/sponsors.yml
#    - topic_repos: ../en/data/topic_repos.yml
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
#          extensions:
#          - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: true
          preload_modules:
          - aiohttp
          - boto3
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

