[tool.poetry]
name = "async_boto"
version = "0.0.1"
description = "Python pckage to asyncronous interact with AWS"
authors = ["Christopher Müller"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "~2.1.1"
aiohttp = "~3.8.5"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-mock ="~3.2.0"
pytest-cov ="~2.11.1"
pytest-freezegun="~0.4.2"
freezegun ="~1.2.1"
pytest-asyncio = "~0.20.3"
ruff= "~0.0.282"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
