[tox]
envlist = linting
          commitizen
          local
isolated_build = true

[testenv:local]
basepython=python3.12
passenv = *
setenv=
	AWS_DEFAULT_REGION=eu-central-1
    AWS_ACCESS_KEY_ID=dummy_access_key
    AWS_SECRET_ACCESS_KEY=dummy_secret_key
    AWS_SESSION_TOKEN=dummy_session_token
    mode=local
    SKIP_SPECIAL_TESTS = 1
deps =  pytest==8.3.5
        pytest-asyncio==0.25.3
        localstack==4.2.0
        pytest-cov==6.0.0
commands =
           localstack --version
           localstack start -d
           pytest {posargs} -x --cov=async_boto --cov-report=term-missing --cov-report html:cov_html
		   #coverage report --fail-under=100

[testenv:cloud]
basepython=python3.12
passenv = *
setenv=
	AWS_DEFAULT_REGION=eu-central-1
deps =  pytest==8.3.5
        pytest-asyncio==0.25.3
        pytest-cov==6.0.0
commands =
           pytest {posargs} -x --cov=async_boto --cov-report=term-missing --cov-report html:cov_html
		   #coverage report --fail-under=100

[testenv:format]
basepython=python3.12
deps = ruff
commands =
    ruff check --fix async_boto
    ruff format async_boto

[testenv:commitizen]
allowlist_externals = git
basepython=python3.12
deps = commitizen==3.16.0
commands =
    cz check --rev-range origin/main..HEAD

[testenv:linting]
basepython=python3.12
deps = ruff
       commitizen==3.16.0
commands =
    ruff format --check async_boto
    ruff check async_boto