[tox]
envlist = py38
isolated_build = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root
commands =
    poetry run pytest {posargs} -x --cov=async_boto tests --cov-report=term-missing --cov-report html:cov_html --import-mode importlib
    coverage report --fail-under=95
    ruff check src