[tox]
envlist = linting
          commitizen
isolated_build = true

[testenv]
passenv = *
setenv =
    AWS_DEFAULT_REGION=eu-central-1

[testenv:format]
basepython=python3.12
deps = ruff
commands =
    ruff check --fix async_boto
    ruff format async_boto

[testenv:commitizen]
allowlist_externals = git
basepython=python3.12
deps = commitizen==3.16.0
commands =
    cz check --rev-range origin/main..HEAD

[testenv:linting]
basepython=python3.12
deps = ruff
       commitizen==3.16.0
commands =
    ruff format --check async_boto
    ruff check async_boto