name: tox

on:
  pull_request:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python3.11 -m pip install --upgrade pip
        python3.12 -m pip install --upgrade pip
        python3.13 -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      run: |
        tox -r -p